config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  # users controller
  resources :users do
    get "posts" => "users#my_posts", :as => 'user_posts'
  end
  
  
  # posts controller
  resources :posts

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

    has_many :authorships
    has_many :users, through: :authorships


    validates :title, presence: true
    validates :content, presence: true
    
    # validate :image_type
    validates :images, attached: true, content_type: %i[png jpg jpeg]

    has_many_attached :images

    def thumbnail input
        return self.images[input]
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :authorships
  has_many :posts, through: :authorships



  # validates :name, presence: true
  EMAIL_FORMAT_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true

  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :require_author, only: [:edit, :update, :destroy]

    def index
        @posts = Post.all.order("created_at DESC")
    end
  
    def new
        @post = Post.new
    end
  
    def create
        @post = Post.new(post_params)
    
        respond_to do |format|
            if @post.save
                format.html { redirect_to @post}
                format.json { render :show, status: :created, location: @post }
            else
                format.html { render :new }
                format.json { render json: @post.errors, status: :unprocessable_entity }
             end
        end
    end
  
    def require_author
        redirect_to(@post) unless @post.users ==
        @post.users.each do |user|
            user.id
        end
    end

    def set_post
        @post = Post.find(params[:id])
    end

    def show
        @post = Post.find(params[:id])
    end
  
    def update
        @post = Post.find(params[:id])
  
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
  
    def edit
        @post = Post.find(params[:id])
    end
  
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
  
    private
  
    def post_params
        params.require(:post).permit(:title, :user_ids, :author, :content, images: [], )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new
  # end

  # def create
  #   user = User.find_by(email: params[:session][:email])
  #     session[:user_id] = user.id
  #     redirect_to user
  # end

  # def destroy
  #   session.delete(:user_id)
  #   @current_user = nil
  #   redirect_to posts_path
  # end

  # def new
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
        @users = User.all.order("created_at DESC")
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
  
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end

    def my_posts
        user = User.find(params[:user_id])
        @posts = user.posts.order("created_at DESC")
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
  
        redirect_to users_path
  
    end


    private
  
    def user_params
        params.fetch(:user, {}).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Blog', root_path, class: "navbar-item" %>
              <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
                <%# if else %>
                <% if user_signed_in? %><%=link_to current_user.name, user_user_posts_path(current_user), class:"navbar-item" %>
                    <div class="navbar-item">|</div>
                    <%= link_to 'Log out', destroy_user_session_path, method: :delete , class:"navbar-item"%>
                <% else %>
                    <%= link_to 'Log in', new_user_session_path, class:"navbar-item" %>
                    <div class="navbar-item">|</div>
                    <%= link_to 'Sign up', new_user_registration_path, class:"navbar-item" %>
                  <% end %>

              </div>
            </div>
          </div>
        </nav>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>


<%# Ruby toastr scripts %>
<% unless flash.empty? %>
   <script type="text/javascript">
      <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   	 toastr['<%= type %>']('<%= f[1] %>');
   <% end %>
   </script>
<% end %>

<!-- Devise scripts -->



    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="">
      <%= f.label :user_ids, 'Author(s)' %> <br/>
      <%= f.collection_select :user_ids, User.order(:name), :id, :name, {}, {multiple: true} %>
    </div>
  </div>

<br />

  <div class="field">
    <div class="control">
      <%= f.file_field :images, input_html: { class: 'images' }, wrapper: false, label_html: { class: 'images' }, multiple: true %>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Create new post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>
<div class="section">
<%= simple_form_for @post do |f| %>

  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="">
      <%= f.label :user_ids, 'Author(s)' %> <br/>
      <%= f.collection_select :user_ids, User.order(:name), :id, :name, {}, {multiple: true} %>
    </div>
  </div>

<br />
  <div class="field">
    <div class="control">
      <%= f.file_field :images, input_html: { class: 'images' }, wrapper: false, label_html: { class: 'images' }, multiple: true %>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Update post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/index.html.erb
<% content_for :page_title,  "Home" %>

<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
        <div class="card-content">
          <div class="main">
            <div class="title content media-left">
            <% if post.images.attached? %>
              <%= link_to (image_tag post.images.first, style:'width:200px; height: auto;'), post %>
            </div>
            <% end %>
            <div class="content main">
              <p class="title is-4"><%= link_to post.title, post %></p>
            </div>
          </div>
          <div class="content">
              <%= post.content %>
          </div>
        </div>
		  </div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
    <div class="container" style="position: center">
        <nav class="level">
          <!-- Left side -->
          <div class="level-left">
            <p class="level-item">
                <strong>Author: 
                  <% @post.users.each do |user| %>
                    <span><%= user.name %></span>
                  <%end%>
                </strong>
            </p>
          </div>
          <!-- Right side -->

          <!-- Only show if the current user is the poster -->
          <% if @post.users %>
            <div class="level-right">
                <p class="level-item">
                  <%= link_to "Edit", edit_post_path(@post), class:"button" %>
                </p>
                <p class="level-item">
                  <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
                  </p>
            </div>
          <% end %>
        </nav>
        <hr/>

        <div class="content">
            <%= @post.content %>
        </div>
        <% if @post.images.attached? %>
          <% (0...@post.images.count).each do |image| %>
          <div style="width: 300px;">
              <%= image_tag(@post.thumbnail(image), style:'width:100%; height: auto;')%>
          </div>
          <% end %>
        <% end %>
    </div>
</section>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="danger"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="control">
    <%= form.label :name %> 
    <%= form.text_field :name, class: 'input' %> 
</div>
    </div>
<div class="field">
    <div class="control">
    <%= form.label :email %> 
    <%= form.email_field :email, class: 'input' %> 
</div>
    </div>
<div class="field">
    <div class="control">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'input' %>
</div>
    </div>
<div class="field">
    <div class="control">
    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation, class: 'input' %>
</div>
    </div>
    <%= form.submit "Create User", class: "button is-primary" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/my_posts.html.erb
<% content_for :page_title, current_user.name %>

<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
        <div class="card-content">
          <div class="main">
            <div class="title content media-left">
            <% if post.images.attached? %>
              <%= link_to (image_tag post.images.first, style:'width:200px; height: auto;'), post %>
            </div>
            <% end %>
            <div class="content main">
              <p class="title is-4"><%= link_to post.title, post %></p>
            </div>
          </div>
          <div class="content">
              <%= post.content %>
          </div>
        </div>
		  </div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<% content_for :page_title, "Create a new user" %>
<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :page_title, current_user.name %>

<section class="section"> Change this routs to myPost
</section>